
package animelist;

import java.awt.*;
import javax.swing.*;

public class Search extends javax.swing.JFrame {
    
    private AnimeWindow Window;
    private ImageIcon icon;
    private String[] header = new String [] {"ID", "Name", "Type", "Lenght", "Weight", "Times"};
    
    /** Creates new form Search */
    public Search(AnimeWindow window) {
        initComponents();
        Window = window;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        SearchScrollPane = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        IDButton = new javax.swing.JButton();
        SearchTextField = new javax.swing.JTextField();
        NameButton = new javax.swing.JButton();
        TypeButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox();
        WeightButton = new javax.swing.JButton();
        weightComboBox = new javax.swing.JComboBox();
        SaveButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paieska");

        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Lenght", "Weight", "Times"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPicture(evt);
            }
        });
        SearchScrollPane.setViewportView(SearchTable);
        SearchTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        SearchTable.getColumnModel().getColumn(1).setPreferredWidth(200);
        SearchTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        SearchTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        SearchTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        SearchTable.getColumnModel().getColumn(5).setPreferredWidth(50);

        MainTabbedPane.addTab("Paieska", SearchScrollPane);

        IDButton.setText("Pagal ID");
        IDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDButtonActionPerformed(evt);
            }
        });

        NameButton.setText("Pagal name");
        NameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameButtonActionPerformed(evt);
            }
        });

        TypeButton.setText("Pagal type");
        TypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeButtonActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Movie", "OVA", "TV" }));
        typeComboBox.setSelectedItem("TV");

        WeightButton.setText("Pagal weight");
        WeightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightButtonActionPerformed(evt);
            }
        });

        weightComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        imagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        imageLabel.setText(" ");

        org.jdesktop.layout.GroupLayout imagePanelLayout = new org.jdesktop.layout.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, imageLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout MainPanelLayout = new org.jdesktop.layout.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(MainPanelLayout.createSequentialGroup()
                        .add(IDButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(NameButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, typeComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TypeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(weightComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(WeightButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(SearchTextField)
                            .add(SaveButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                    .add(MainPanelLayout.createSequentialGroup()
                        .add(MainTabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(53, 53, 53)
                        .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(MainTabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(WeightButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .add(SearchTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(IDButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .add(NameButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .add(TypeButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .add(2, 2, 2)
                .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(typeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(MainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(weightComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(SaveButton)))
                .addContainerGap())
            .add(MainPanelLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(imagePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(MainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDButtonActionPerformed
        Window.getOperations().makeIDLists(SearchTextField.getText());
        clearSearchTable(Window.getOperations().getTempList().size());
        Window.getOperations().SpecialshowImputedEntities(Window.getOperations().getTempList(), SearchTable);
    }//GEN-LAST:event_IDButtonActionPerformed

    private void NameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameButtonActionPerformed
        Window.getOperations().makeNameLists(SearchTextField.getText());
        clearSearchTable(Window.getOperations().getTempList().size());
        Window.getOperations().SpecialshowImputedEntities(Window.getOperations().getTempList(), SearchTable);
    }//GEN-LAST:event_NameButtonActionPerformed

    private void TypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeButtonActionPerformed
        Window.getOperations().makeTypeLists(typeComboBox.getSelectedItem().toString());
        clearSearchTable(Window.getOperations().getTempList().size());
        Window.getOperations().SpecialshowImputedEntities(Window.getOperations().getTempList(), SearchTable);
    }//GEN-LAST:event_TypeButtonActionPerformed

    private void WeightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightButtonActionPerformed
        Window.getOperations().makeWeightLists(weightComboBox.getSelectedItem().toString());
        clearSearchTable(Window.getOperations().getTempList().size());
        Window.getOperations().SpecialshowImputedEntities(Window.getOperations().getTempList(), SearchTable);
    }//GEN-LAST:event_WeightButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        Window.getOperations().saveSearchList();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void showPicture(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPicture
        try {
            int row = SearchTable.getSelectedRow();
            //jei kas nors pasirinkta
            if (row != -1){
                String temp = SearchTable.getValueAt(row, 1).toString();
                String realName = temp.substring(2);
                icon = new ImageIcon(Window.getOperations().getPictureDirektorija()+realName+".jpg");
                imageLabel.setIcon(icon);
            }
        } catch (Exception e){
            System.out.println(e.toString());
            System.out.println("(diagnostika):klaida atidarant faila!");
            icon = new ImageIcon(Window.getOperations().getPictureDirektorija()+"error.JPG");
            imageLabel.setIcon(icon);
        } 
    }//GEN-LAST:event_showPicture

private void clearSearchTable(int size){
    //perdarom lentele
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(header, size){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
    SearchTable.setModel(model);
    SearchTable.getColumnModel().getColumn(0).setPreferredWidth(30);
    SearchTable.getColumnModel().getColumn(1).setPreferredWidth(200);
    SearchTable.getColumnModel().getColumn(2).setPreferredWidth(50);
    SearchTable.getColumnModel().getColumn(3).setPreferredWidth(50);
    SearchTable.getColumnModel().getColumn(4).setPreferredWidth(50);
    SearchTable.getColumnModel().getColumn(5).setPreferredWidth(50);
    //SearchTable.getModel().
    
}    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton NameButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane SearchScrollPane;
    private javax.swing.JTable SearchTable;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton TypeButton;
    private javax.swing.JButton WeightButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JComboBox weightComboBox;
    // End of variables declaration//GEN-END:variables
    
}
